export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const FETCHING_TASKS_START = 'FETCHING_TASK_START';
export const FETCHING_TASKS_SUCCESS = 'FETCHING_TASK_SUCCESS';
export const FETCHING_TASKS_FAIL = 'FETCHING_TASK_FAIL';
