export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const FETCHING_TASKS_START = "FETCHING_TASK_START";
export const FETCHING_TASKS_SUCCESS = "FETCHING_TASK_SUCCESS";
export const FETCHING_TASKS_FAIL = "FETCHING_TASK_FAIL";

export const CREATING_TASK_START = "CREATING_TASK_START";
export const CREATING_TASK_SUCCESS = "CREATING_TASK_SUCCESS";
export const CREATING_TASK_FAIL = "CREATING_TASK_FAIL";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export const UPDATE_TASK_START = "UPDATE_TASK_START";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const MOVE_TASK = "MOVE_TASK";
